version: '3.5'
services:
    webservice:
        build: .
        command: python3 app.py
        container_name: graphql-demo
        image: docker.sltc.local/graphql-demo:local
        ports:
            - '5000:5000'
        volumes:
            - .:/app
networks:
    default:
        external:
            name: simple-network
